language: cpp

compiler:
- clang
- gcc

os:
- osx
- linux

dist: trusty
osx_image: xcode8.2


before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update  ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5 ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/qt5/bin:$PATH" ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  sudo add-apt-repository -y ppa:beineri/opt-qt58-trusty ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  sudo apt-get update -qq ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  sudo apt-get install -y qt58base qt58svg ; fi 
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  source /opt/qt58/bin/qt58-env.sh ; fi 

script: 
 - ./build.sh 



